# render.yaml
services:
  - type: web
    name: pickbazar-api
    env: php
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      cp .env.example .env
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan migrate --force
      php artisan vendor:publish --provider="CloudinaryLabs\CloudinaryLaravel\CloudinaryServiceProvider" --tag="cloudinary-laravel-config"
      php artisan storage:link
      php artisan marvel:install --force
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: PickBazar
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app-name.onrender.com/backend
      # Database configuration
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      # Cloudinary configuration
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # Storage configuration
      - key: FILESYSTEM_DISK
        value: public
      # Add your Stripe configuration
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      # Add your Mail configuration
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
    disk:
      name: pickbazar-storage
      mountPath: /var/www/pickbazar/api/storage
      sizeGB: 1